version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - ./hdfs/namenode:/hadoop/dfs/name
    environment:
      CLUSTER_NAME: test
      HADOOP_OPTS: "-Ddfs.blocksize=67108864" # Set the HDFS block size of 64MB
    env_file:
      - ./hadoop.env
    deploy:
      resources:
        limits:
          memory: 1G

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    volumes:
      - ./hdfs/datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      HADOOP_OPTS: "-Ddfs.blocksize=67108864" 
    env_file:
      - ./hadoop.env
    deploy:
      resources:
        limits:
          memory: 2G
  
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: spark-master
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      SPARK_DRIVER_MEMORY: 2G
      SPARK_EXECUTOR_MEMORY: 2G

    depends_on:
      - namenode
      - datanode1
    deploy:
      resources:
        limits:
          memory: 2G

  spark-worker-1:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: spark-worker-1
    container_name: spark-worker-1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "0.0.0.0:8081:8081"
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2G
      SPARK_MASTER_URL: spark://spark-master:7077

volumes:
  hadoop_namenode:
  hadoop_datanode1: